---

services:
  fbm-rss:
    build: .
    container_name: fbm-rss
    restart: always
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      REFRESH_INTERVAL: "${REFRESH_INTERVAL:-15}"
      STALE_AD_AGE: "${STALE_AD_AGE:-14}"
      RSS_EXTERNAL_DOMAIN: "${RSS_EXTERNAL_DOMAIN:-http://localhost:5000}"
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}/config/config.json:/app/config/config.json