#docker-compose up -d
services:
  fb-mp-rss:
    build: . # Build from local Dockerfile
    image: bethekind/fb-mp-rss:latest # Specifies the image to use or build
    container_name: fb-mp-rss
    restart: always
    environment:
      CONFIG_FILE: /app/config.json # Path for config file inside the container
      STALE_AD_AGE: 14
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/app/config.json # Mounts host's ./config.json to /app/config.json in container