---

services:
  fb-mp-rss:
    build: .
    image: bethekind/fb-mp-rss:latest
    container_name: fb-mp-rss
    restart: always
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      CONFIG_FILE: "${CONFIG_FILE:-/app/config.json}"
      REFRESH_INTERVAL: "${REFRESH_INTERVAL:-15}"
      STALE_AD_AGE: "${STALE_AD_AGE:-14}"
      RSS_EXTERNAL_DOMAIN: "${RSS_EXTERNAL_DOMAIN:-http://localhost:5000}"
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/app/config.json