---

services:
  fb-mp-rss:
    build: .
    image: bethekind/fb-mp-rss:latest
    container_name: fb-mp-rss
    restart: always
    environment:
      CONFIG_FILE: /app/config.json
      REFRESH_INTERVAL: ${REFRESH_INTERVAL}
      STALE_AD_AGE: 14
      RSS_EXTERNAL_DOMAIN: ${RSS_EXTERNAL_DOMAIN}
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/app/config.json